// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ82BjGiAd4-tQkcmMuOWDeks-xQf2N1A',
    appId: '1:1045699376267:web:7dd738a0ae8bd8c1f1908e',
    messagingSenderId: '1045699376267',
    projectId: 'docflow-app',
    authDomain: 'docflow-app.firebaseapp.com',
    storageBucket: 'docflow-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ABtxXWNVFVxVQwiA8Lo9QjWmq-Me5h0',
    appId: '1:1045699376267:android:f2e2319dd2ffc5ccf1908e',
    messagingSenderId: '1045699376267',
    projectId: 'docflow-app',
    storageBucket: 'docflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHzDT_KiLoZ8gqvgNhFrWfJ6LvrU9ZHg',
    appId: '1:1045699376267:ios:c924e26009a8f031f1908e',
    messagingSenderId: '1045699376267',
    projectId: 'docflow-app',
    storageBucket: 'docflow-app.firebasestorage.app',
    iosBundleId: 'com.example.docflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqHzDT_KiLoZ8gqvgNhFrWfJ6LvrU9ZHg',
    appId: '1:1045699376267:ios:c924e26009a8f031f1908e',
    messagingSenderId: '1045699376267',
    projectId: 'docflow-app',
    storageBucket: 'docflow-app.firebasestorage.app',
    iosBundleId: 'com.example.docflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ82BjGiAd4-tQkcmMuOWDeks-xQf2N1A',
    appId: '1:1045699376267:web:3db996a6bb71f9f8f1908e',
    messagingSenderId: '1045699376267',
    projectId: 'docflow-app',
    authDomain: 'docflow-app.firebaseapp.com',
    storageBucket: 'docflow-app.firebasestorage.app',
  );
}
